import { describe, expect, it } from "vitest";

import { getPortalSnapshot } from "@/lib/portal-data";

describe("case classification", () => {
  it("assigns stable issue categories to core China fiduciary-duty cases", async () => {
    const snapshot = await getPortalSnapshot();
    const caseMap = new Map(snapshot.cases.map((record) => [record.id, record]));

    expect(caseMap.get("cn-reference-case-monitor-representative-suit-shanghai")?.classificationId).toBe(
      "representative-action"
    );
    expect(caseMap.get("cn-database-case-related-transaction-gao-cheng")?.classificationId).toBe(
      "related-party-misappropriation"
    );
    expect(caseMap.get("cn-reference-case-xiang-zaozhuang-taxi-energy-supply")?.classificationId).toBe(
      "related-party-misappropriation"
    );
    expect(caseMap.get("cn-reference-case-kou-guo-henan-education-asset-sale")?.classificationId).toBe(
      "representative-action"
    );
    expect(
      caseMap.get("cn-reference-case-shanghai-investment-bio-related-resolution")?.classificationId
    ).toBe("related-party-misappropriation");
    expect(
      caseMap.get("cn-reference-case-yiming-jinshengli-related-transaction-offset")?.classificationId
    ).toBe("related-party-misappropriation");
    expect(caseMap.get("cn-database-case-change-registration-chen-moufei")?.classificationId).toBe(
      "legal-representative-and-seal-control"
    );
    expect(caseMap.get("cn-typical-case-certificate-preservation-japan-a")?.classificationId).toBe(
      "legal-representative-and-seal-control"
    );
    expect(caseMap.get("cn-database-case-certificate-return-shanghai-pan")?.classificationId).toBe(
      "legal-representative-and-seal-control"
    );
    expect(caseMap.get("cn-gazette-case-thumb-legal-representative-publicity")?.classificationId).toBe(
      "legal-representative-and-seal-control"
    );
    expect(caseMap.get("cn-gazette-case-zhenbang-apparent-representation-guarantee")?.classificationId).toBe(
      "legal-representative-and-seal-control"
    );
    expect(
      caseMap.get("cn-gazette-case-hk-xinjianye-representative-before-registration")?.classificationId
    ).toBe("legal-representative-and-seal-control");
    expect(caseMap.get("cn-database-case-false-seal-legal-representative-real-estate")?.classificationId).toBe(
      "legal-representative-and-seal-control"
    );
    expect(caseMap.get("cn-reference-case-spring-auto-establishment-registration")?.classificationId).toBe(
      "registration-legal-representative"
    );
    expect(caseMap.get("cn-reference-case-limou-financing-lease-scope-registration")?.classificationId).toBe(
      "registration-legal-representative"
    );
    expect(caseMap.get("cn-reference-case-wanmougong-enterprise-name-registration")?.classificationId).toBe(
      "registration-legal-representative"
    );
    expect(caseMap.get("cn-database-case-listed-buyback-vam-nanjing")?.classificationId).toBe(
      "vam-disputes"
    );
    expect(caseMap.get("cn-gazette-case-vam-haifu-investment")?.classificationId).toBe(
      "vam-disputes"
    );
    expect(caseMap.get("cn-database-case-vam-shanghai-preemption-buyback")?.classificationId).toBe(
      "vam-disputes"
    );
    expect(caseMap.get("cn-database-case-equity-security-nominee-vote")?.classificationId).toBe(
      "shareholder-status-equity-ownership"
    );
    expect(caseMap.get("cn-reference-case-vam-zhongnan-ipo-restoration")?.classificationId).toBe(
      "vam-disputes"
    );
    expect(caseMap.get("cn-reference-case-vam-hu-xiufang-drawer")?.classificationId).toBe(
      "vam-disputes"
    );
    expect(caseMap.get("cn-reference-case-vam-huyue-neeq-delisting")?.classificationId).toBe(
      "vam-disputes"
    );
    expect(caseMap.get("cn-reference-case-vam-huagong-buyback")?.classificationId).toBe(
      "vam-disputes"
    );
    expect(caseMap.get("cn-reference-case-vam-zhang-dongju-damages")?.classificationId).toBe(
      "vam-disputes"
    );
    expect(caseMap.get("cn-reference-case-vam-gaoci-neeq-invalid")?.classificationId).toBe(
      "vam-disputes"
    );
    expect(caseMap.get("cn-reference-case-fang-siwei-related-transaction-monitor")?.classificationId).toBe(
      "representative-action"
    );
    expect(caseMap.get("cn-reference-case-lvyuan-patent-transfer-loyalty")?.classificationId).toBe(
      "fiduciary-loyalty"
    );
    expect(caseMap.get("cn-reference-case-baolu-vehicle-reward-duty-boundary")?.topics).toContain(
      "legal-representative-and-seal-control"
    );
    expect(caseMap.get("cn-reference-case-baolu-vehicle-reward-duty-boundary")?.classificationId).toBe(
      "fiduciary-loyalty"
    );
    expect(caseMap.get("cn-reference-case-shanxi-property-and-monitor-zhuyue")?.topics).toContain(
      "legal-representative-and-seal-control"
    );
    expect(caseMap.get("cn-reference-case-shanxi-property-and-monitor-zhuyue")?.classificationId).toBe(
      "related-party-misappropriation"
    );
    expect(caseMap.get("cn-reference-case-dazhihui-derivative-recovery")?.classificationId).toBe(
      "listed-company-governance"
    );
    expect(caseMap.get("cn-reference-case-st-moden-fund-occupation-derivative")?.classificationId).toBe(
      "listed-company-governance"
    );
    expect(caseMap.get("cn-reference-case-hongshida-zhangchen-company-harm")?.classificationId).toBe(
      "related-party-misappropriation"
    );
    expect(caseMap.get("cn-reference-case-yuyao-job-invention-loyalty")?.classificationId).toBe(
      "related-party-misappropriation"
    );
    expect(caseMap.get("cn-reference-case-taian-ret-fund-occupation-derivative")?.classificationId).toBe(
      "listed-company-governance"
    );
    expect(caseMap.get("cn-reference-case-st-lutong-fund-occupation-derivative")?.classificationId).toBe(
      "listed-company-governance"
    );
    expect(caseMap.get("cn-reference-case-supervisor-noncompete-binhu")?.classificationId).toBe(
      "fiduciary-loyalty"
    );
    expect(caseMap.get("cn-guiding-case-15-corporate-veil")?.classificationId).toBe(
      "corporate-veil-piercing"
    );
    expect(caseMap.get("cn-guiding-case-215-environmental-veil-piercing")?.classificationId).toBe(
      "corporate-veil-piercing"
    );
    expect(caseMap.get("cn-reference-case-closure-operator-liquidation-liability")?.classificationId).toBe(
      "corporate-veil-piercing"
    );
    expect(caseMap.get("cn-gazette-case-xinda-tailai-affiliated-company-veil")?.classificationId).toBe(
      "corporate-veil-piercing"
    );
    expect(caseMap.get("cn-gazette-case-ying-gaofeng-jiameide-one-person-veil")?.classificationId).toBe(
      "corporate-veil-piercing"
    );
    expect(caseMap.get("cn-gazette-case-shao-ping-kuntong-xingtongda-veil")?.classificationId).toBe(
      "corporate-veil-piercing"
    );
    expect(caseMap.get("cn-reference-case-jiachen-haima-burden-allocation-veil")?.classificationId).toBe(
      "corporate-veil-piercing"
    );
    expect(caseMap.get("cn-reference-case-taiwan-plastics-ningbo-import-export-veil")?.classificationId).toBe(
      "corporate-veil-piercing"
    );
    expect(caseMap.get("cn-reference-case-meizhou-salt-baked-chicken-agency-veil")?.classificationId).toBe(
      "corporate-veil-piercing"
    );
    expect(caseMap.get("cn-reference-case-luo-weikang-nike-affiliate-veil")?.classificationId).toBe(
      "corporate-veil-piercing"
    );
    expect(
      caseMap.get("cn-reference-case-guangzhou-dashun-jiangmen-fengpin-weichang-veil")?.classificationId
    ).toBe("corporate-veil-piercing");
    expect(caseMap.get("cn-reference-case-guangzhou-construction-benefit-transfer-veil")?.classificationId).toBe(
      "corporate-veil-piercing"
    );
    expect(caseMap.get("cn-reference-case-kunshan-shell-switching-horizontal-veil")?.classificationId).toBe(
      "corporate-veil-piercing"
    );
    expect(caseMap.get("cn-reference-case-zibo-sichuang-glade-fushide-beisida-veil")?.classificationId).toBe(
      "corporate-veil-piercing"
    );
    expect(caseMap.get("cn-guiding-case-130-zangjinge-entrusted-pollution")?.classificationId).toBe(
      "corporate-social-responsibility"
    );
    expect(caseMap.get("cn-guiding-case-23-expired-food-punitive-damages")?.classificationId).toBe(
      "corporate-social-responsibility"
    );
    expect(caseMap.get("cn-guiding-case-182-bonus-approval-labor-pay")?.classificationId).toBe(
      "corporate-social-responsibility"
    );
    expect(caseMap.get("cn-guiding-case-237-platform-outsourcing-labor")?.classificationId).toBe(
      "corporate-social-responsibility"
    );
    expect(caseMap.get("cn-reference-case-fuhai-cherry-air-pollution")?.classificationId).toBe(
      "corporate-social-responsibility"
    );
    expect(caseMap.get("cn-reference-case-hyundai-emissions-public-interest-trust")?.classificationId).toBe(
      "corporate-social-responsibility"
    );
    expect(caseMap.get("cn-reference-case-pingchuan-three-no-diet-product")?.classificationId).toBe(
      "corporate-social-responsibility"
    );
    expect(
      caseMap.get("cn-reference-case-liang-cook-apprentice-gender-discrimination")?.classificationId
    ).toBe("corporate-social-responsibility");
    expect(caseMap.get("cn-reference-case-hbv-carrier-employment-discrimination")?.classificationId).toBe(
      "corporate-social-responsibility"
    );
    expect(caseMap.get("cn-reference-case-meihekou-heating-rescue-health")?.classificationId).toBe(
      "corporate-social-responsibility"
    );
    expect(caseMap.get("cn-reference-case-nansha-port-safety-injury")?.classificationId).toBe(
      "corporate-social-responsibility"
    );
    expect(caseMap.get("cn-guiding-case-96-shareholder-status")?.classificationId).toBe(
      "shareholder-status-equity-ownership"
    );
    expect(caseMap.get("cn-gazette-case-beneficial-owner-zhang-jianzhong")?.classificationId).toBe(
      "shareholder-status-equity-ownership"
    );
    expect(caseMap.get("cn-gazette-case-cheng-junping-foreign-beneficial-owner-status")?.classificationId).toBe(
      "shareholder-status-equity-ownership"
    );
    expect(caseMap.get("cn-database-case-lv-gansu-investment-shareholder-status")?.classificationId).toBe(
      "shareholder-status-equity-ownership"
    );
    expect(caseMap.get("cn-reference-case-qinzhou-impersonated-employee-no-status")?.classificationId).toBe(
      "shareholder-status-equity-ownership"
    );
    expect(caseMap.get("cn-gazette-case-wang-qinjie-contribution-extension-creditor-protection")?.classificationId).toBe(
      "capital-contribution-maintenance"
    );
    expect(caseMap.get("cn-database-case-lu-cao-low-price-transfer-contribution")?.classificationId).toBe(
      "capital-contribution-maintenance"
    );
    expect(caseMap.get("cn-database-case-wen-sichuan-subscription-limitations")?.classificationId).toBe(
      "capital-contribution-maintenance"
    );
    expect(caseMap.get("cn-reference-case-zhao-liangchen-capital-withdrawal-offset")?.classificationId).toBe(
      "capital-contribution-maintenance"
    );
    expect(caseMap.get("cn-reference-case-linzi-malicious-extension-acceleration")?.classificationId).toBe(
      "capital-contribution-maintenance"
    );
    expect(caseMap.get("cn-reference-case-jimo-unpaid-contribution-liability")?.classificationId).toBe(
      "capital-contribution-maintenance"
    );
    expect(caseMap.get("cn-reference-case-wang-xu-change-to-ip-contribution")?.classificationId).toBe(
      "capital-contribution-maintenance"
    );
    expect(caseMap.get("cn-reference-case-yuehua-defective-capital-reduction")?.classificationId).toBe(
      "capital-contribution-maintenance"
    );
    expect(
      caseMap.get("cn-reference-case-zhejiang-reduction-not-direct-execution")?.classificationId
    ).toBe("capital-contribution-maintenance");
    expect(
      caseMap.get("cn-reference-case-today-seeds-zero-price-transfer-reduction")?.classificationId
    ).toBe("capital-contribution-maintenance");
    expect(
      caseMap.get("cn-gazette-case-bafeite-state-owned-off-market-transfer-invalid")?.classificationId
    ).toBe("general-corporate-governance");
    expect(
      caseMap.get("cn-gazette-case-changcheng-jilin-gratuitous-transfer-creditor-protection")?.classificationId
    ).toBe("general-corporate-governance");
    expect(caseMap.get("cn-gazette-case-fengfeng-state-capital-loan-boundary")?.classificationId).toBe(
      "general-corporate-governance"
    );
  });

  it("keeps comparative and partnership cases in separate buckets", async () => {
    const snapshot = await getPortalSnapshot();
    const caseMap = new Map(snapshot.cases.map((record) => [record.id, record]));

    expect(caseMap.get("cn-gazette-case-partnership-share-transfer-xing-furong")?.classificationId).toBe(
      "partnership-governance"
    );
    expect(caseMap.get("sg-case-goh-jin-hian-directors-duties")?.classificationId).toBe(
      "comparative-corporate"
    );
  });
});
